build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:latest
  amd64: ghcr.io/home-assistant/amd64-base:latest
  armhf: ghcr.io/home-assistant/armhf-base:latest
  armv7: ghcr.io/home-assistant/armv7-base:latest
  i386: ghcr.io/home-assistant/i386-base:latest
squash: false
labels:
  org.opencontainers.image.title: "Homepage"
  org.opencontainers.image.description: "A modern, fully static, fast, secure, fully proxied, highly customizable application dashboard"
  org.opencontainers.image.vendor: "ItsDyno"
  org.opencontainers.image.authors: "ItsDyno"
  org.opencontainers.image.licenses: "MIT"
  org.opencontainers.image.url: "https://gethomepage.dev"
  org.opencontainers.image.source: "https://github.com/ItsDyno/ItsDyno-HA-Addons"
  org.opencontainers.image.documentation: "https://github.com/ItsDyno/ItsDyno-HA-Addons/blob/main/homepage/DOCS.md"
